# Numpy

1. numpy 数组 - ndarray
2. 矩阵表示及常用矩阵
3. 常用矩阵操作
   - 矩阵翻转
   - 矩阵转置
   - 矩阵堆叠
4. 广播特性


## numpy数组基本性质及创建

In [1]:
#第一步：导包
%config ZMQInteractiveShell.ast_node_interactivity='all'
%pprint
import numpy as np

Pretty printing has been turned OFF


In [11]:
#随机生成一组ndarray
a1= np.array(np.random.random(50).reshape(2,5,5))
a1

array([[[0.19427649, 0.4121972 , 0.61021175, 0.21390721, 0.80975134],
        [0.72058551, 0.73509859, 0.53588465, 0.13908298, 0.05376091],
        [0.35630348, 0.08378375, 0.01843955, 0.02982232, 0.32426164],
        [0.63577061, 0.18066359, 0.33667736, 0.76415218, 0.70661712],
        [0.81225692, 0.71036617, 0.32127607, 0.98859652, 0.70735732]],

       [[0.72429191, 0.69784999, 0.66359013, 0.27176914, 0.38271549],
        [0.91889721, 0.54709427, 0.48355087, 0.8219358 , 0.19986806],
        [0.42980867, 0.84347997, 0.25223449, 0.74999708, 0.52851646],
        [0.11499926, 0.70621671, 0.76636569, 0.82745603, 0.45431187],
        [0.86844823, 0.44305627, 0.15713882, 0.51573689, 0.29221601]]])

In [6]:
type(a)

<class 'numpy.ndarray'>

In [7]:
# 随机生成array
b= np.random.random((2,2))
b

array([[0.85307457, 0.13963054],
       [0.51258622, 0.80364745]])

In [8]:
# 查看维度
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[2,4,5]]])
a
a.shape

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 4, 5]]])

(2, 2, 3)

In [86]:
a.ndim  #数组轴的个数，轴的个数即为秩

2

In [87]:
a.dtype #一个用于描述数组元素类型的对象。可以用标准Python类型来创造或指定dtype的类型。
#另外，Numpy也提供了自己的类型，如numpy.int32，numpy.int16，numpy.float64等。


dtype('int32')

In [88]:
a.itemsize  #数组每个元素的字节大小。比如一个数组的元素为float64，它的itemsize为8(=64/8)，
#complex32的itemsize为4(=32/8)。这个属性等同于ndarray.dtype.itemsize。

4

In [89]:
a.data  #包含了数组每个实际元素的缓冲器。一般来说我们不会用到这个属性因为我们可以通过索引工具来获取到数组的每个元素的值。

In [9]:
print(a.shape, b.shape, a.dtype, b.dtype)

(2, 2, 3) (2, 2) int32 float64


In [10]:
# astype做类型转换
a.astype(np.float)

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [2., 4., 5.]]])

In [21]:
c= np.arange(36).reshape(6,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [99]:
np.zeros((3,3))  #创建3*3的全0数组，默认类型为float 64
print(np.zeros((3,3)).dtype)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

float64


In [106]:
a_1 = np.array([[1, 2],[3, 4]])
np.zeros_like(a_1)     #返回和a_1形状相同的全0数组

array([[0, 0],
       [0, 0]])

In [94]:
np.ones((3,3))  #全1数组

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
np.ones_like(a_1)

array([[1, 1],
       [1, 1]])

In [108]:
np.empty((2,3))   #创建随机内容的数组  np.empty_like

array([[0.5, 1. , 0. ],
       [1.5, 1. , 0. ]])

**numpy.linspace（start，stop，num = 50(optional)，endpoint = True(optional，True为包含终止点，False不包含)，retstep = False（可选，如True，返回（samples，step），其中step是样本之间的间隔。），dtype = None（输出数组的类型，可选），axis = 0 （用于存储样本的轴，可选））**

返回指定间隔内的等间隔数字。

返回在间隔[ start，stop ] 内计算的num个均匀间隔的样本。

间隔的端点可以选择排除。


In [109]:
np.linspace(2, 3, num = 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [111]:
np.linspace(2.0, 3.0, num = 5, endpoint = True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [112]:
np.linspace(2.0, 3.0, num = 5, retstep = True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [116]:
import math
x = np.linspace( 0, 2* math.pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)

In [124]:
np.random.randint(100)  #返回一个随机整数
#np.random.randint(low, high=None, size=None, dtype=’l’) 
np.random.randint(1,size=(2,2)) 
np.random.randint(1,20,size=(3,5),dtype = 'uint8') 

30

array([[0, 0],
       [0, 0]])

array([[13, 11, 11, 14,  7],
       [ 3, 13, 18, 19,  2],
       [10, 12, 15,  2, 19]], dtype=uint8)

In [120]:
np.random.randn(1)   #通过本函数可以返回一个或一组服从标准正态分布的随机样本值。
np.random.randn(5) 

array([-0.04014978])

array([-0.00829613, -0.61079416,  0.20075273, -0.50497765,  1.25841378])

In [121]:
np.random.rand(5)    #返回一个0-1之间的随机浮点数

array([0.99234108, 0.67431484, 0.82671469, 0.28800956, 0.53419293])

## 数组索引及切片

In [12]:
a
a[0,1]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 4, 5]]])

array([4, 5, 6])

In [18]:
a
a[:,:, 1:3]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 4, 5]]])

array([[[2, 3],
        [5, 6]],

       [[2, 3],
        [4, 5]]])

In [15]:
a
a[:, 1:3]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 4, 5]]])

array([[[4, 5, 6]],

       [[2, 4, 5]]])

In [16]:
a[:, 1:3, :]

array([[[4, 5, 6]],

       [[2, 4, 5]]])

In [23]:
c[2::2,::2]  #开始索引：结尾索引：步长  表示从第3行开始取，取之后间隔为2的所有行，再对列按间隔2取值
c

array([[12, 14, 16],
       [24, 26, 28]])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

## Boolean Indexing

In [25]:
a
a > 2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 4, 5]]])

array([[[False, False,  True],
        [ True,  True,  True]],

       [[False, False,  True],
        [False,  True,  True]]])

In [27]:
a[a>2] #根据条件选择

array([3, 4, 5, 6, 3, 4, 5])

In [28]:
a[a>2] = 0 #根据条件选择数据进行赋值
a

array([[[1, 2, 0],
        [0, 0, 0]],

       [[1, 2, 0],
        [2, 0, 0]]])

## 数学运算

### 广播特性

矩阵运算时自动广播，按照维度多的那个矩阵进行复制

In [35]:
#形状
a.shape
a

(2, 2, 3)

array([[[1, 2, 0],
        [0, 0, 0]],

       [[1, 2, 0],
        [2, 0, 0]]])

In [33]:
d = np.random.random((2,3))
d

array([[0.09626622, 0.32920794, 0.01778159],
       [0.67014781, 0.25172194, 0.02987858]])

In [34]:
a + d  #维度(2,2,3)和(2,3)的array相加，基于广播特性，最后得到维度(2,2,3)的array

array([[[1.09626622, 2.32920794, 0.01778159],
        [0.67014781, 0.25172194, 0.02987858]],

       [[1.09626622, 2.32920794, 0.01778159],
        [2.67014781, 0.25172194, 0.02987858]]])

In [36]:
a-d

array([[[ 0.90373378,  1.67079206, -0.01778159],
        [-0.67014781, -0.25172194, -0.02987858]],

       [[ 0.90373378,  1.67079206, -0.01778159],
        [ 1.32985219, -0.25172194, -0.02987858]]])

In [37]:
a*d

array([[[0.09626622, 0.65841588, 0.        ],
        [0.        , 0.        , 0.        ]],

       [[0.09626622, 0.65841588, 0.        ],
        [1.34029561, 0.        , 0.        ]]])

In [38]:
a / d

array([[[10.38786008,  6.07518758,  0.        ],
        [ 0.        ,  0.        ,  0.        ]],

       [[10.38786008,  6.07518758,  0.        ],
        [ 2.98441625,  0.        ,  0.        ]]])

In [39]:
a + 2   #每个元素+2

array([[[3, 4, 2],
        [2, 2, 2]],

       [[3, 4, 2],
        [4, 2, 2]]])

In [56]:
e = np.random.random((8,6,2,7))
f = np.random.random((8,1,2,1))
(e+f).shape
# note:1d array可以和任意成比例的array广播 但是（8,6,2,7）和（8,3,2,1）这样的不行
#三维、四维及以上情况需尝试，至少2个对应成比例才可能可以广播

(8, 6, 2, 7)

### 统计运算

In [57]:
a
np.sum(a) #全部元素求和

array([[[1, 2, 0],
        [0, 0, 0]],

       [[1, 2, 0],
        [2, 0, 0]]])

8

In [58]:
np.sum(a, axis=0) #按照第1个维度汇总求和

array([[2, 4, 0],
       [2, 0, 0]])

In [59]:
np.sum(a, axis=1) #按照第2个维度汇总求和

array([[1, 2, 0],
       [3, 2, 0]])

In [60]:
np.sum(a, axis=2) #按照第3个维度汇总求和

array([[3, 0],
       [3, 2]])

In [61]:
np.mean(a, axis=1) #按照第2个维度汇总求均值

array([[0.5, 1. , 0. ],
       [1.5, 1. , 0. ]])

numpy还有以下函数：
all，
any，
apply_along_axis，
argmax，
argmin，
argsort，
average，
bincount，
ceil，
clip，
conj，
corrcoef，
cov，
cross，
cumprod，
cumsum，
diff，
dot，
floor，
inner，
lexsort，
max，
maximum，
mean，
median，
min，
minium，
nonzero，
outer，
prod，
re，
round，
sort，
std，
sum，
trace，
transpose，
var，
vdot，
vectorize，
where—np.where（condition,[x,y ] —根据条件从x或y中选择返回的元素。

https://www.jianshu.com/p/3e566f09a0cf


### 矩阵乘法

In [63]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a
b

array([[1, 2],
       [3, 4]])

array([[5, 6],
       [7, 8]])

In [64]:
a.dot(b)     #np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [66]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [67]:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

### 矩阵转置

**数组转置 .T**

In [71]:
data = np.arange(10).reshape(2,5)
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
data.T   #行列互换

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

**轴对换 transpose()**

不传参的话就是维度次序倒转

In [78]:
data = np.arange(24).reshape(2,3,4,1)
data
data.shape

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]],


       [[[12],
         [13],
         [14],
         [15]],

        [[16],
         [17],
         [18],
         [19]],

        [[20],
         [21],
         [22],
         [23]]]])

(2, 3, 4, 1)

In [79]:
data.transpose()
data.transpose().shape

array([[[[ 0, 12],
         [ 4, 16],
         [ 8, 20]],

        [[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]]]])

(1, 4, 3, 2)

In [80]:
data = np.arange(24).reshape(2,3,4)
data

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [81]:
data.transpose(2,1,0)   #等于data.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [83]:
data.transpose(1,0,2)  #把第1维和第2维互换

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

**两轴互换 swapaxes**

In [85]:
data.swapaxes(0,1)   #括号里是轴的编号，即0、1轴互换

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

### 矩阵堆叠

numpy.stack(arrary a, axis=0)

In [127]:
import numpy as np
a=[[1,2,3],
   [4,5,6]]
b=[[1,2,3],
   [4,5,6]]
c=[[1,2,3],
   [4,5,6]]
print("a=",a)
print("b=",b)
print("c=",c)

print("Add one dim，new dim-0")
d=np.stack((a,b,c),axis=0)
print(d)

print("Add one dim，new dim-1")
d=np.stack((a,b,c),axis=1)
print(d)
print("Add one dim，new dim-2")
d=np.stack((a,b,c),axis=2)
print(d)


a= [[1, 2, 3], [4, 5, 6]]
b= [[1, 2, 3], [4, 5, 6]]
c= [[1, 2, 3], [4, 5, 6]]
Add one dim，new dim-0
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Add one dim，new dim-1
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]]
Add one dim，new dim-2
[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]


numpy.vstack(array a, array b)

把b矩阵在a的基础上扩充行—vertical 垂直方向拼接

In [126]:
import numpy as np

a = np.floor(10*np.random.random((3, 3)))
print(a)
print("=================")
b = np.floor(10*np.random.random((3, 3)))
print(b)
print("=================")
print(np.vstack((a, b)))

[[9. 3. 7.]
 [4. 5. 4.]
 [3. 4. 1.]]
[[2. 6. 8.]
 [1. 6. 5.]
 [0. 8. 1.]]
[[9. 3. 7.]
 [4. 5. 4.]
 [3. 4. 1.]
 [2. 6. 8.]
 [1. 6. 5.]
 [0. 8. 1.]]


numpy.hstack(array a, array b)

把b矩阵在a的基础上扩充列—horizontal水平方向拼接

In [ ]:
import numpy as np

a = np.floor(10*np.random.random((3, 3)))
print(a)
print("=================")
b = np.floor(10*np.random.random((3, 3)))
print(b)
print("=================")
print(np.hstack((a, b)))

numpy.column_stack(array a)

In [128]:
import numpy as np
from numpy import newaxis

a = np.floor(10*np.random.random((3, 3)))
print(a)
print("----------------")
b = np.floor(10*np.random.random((3, 3)))
print(b)
print("----------------")
print(np.column_stack((a, b)))
print("----------------")
a = np.array([4., 2.])
b = np.array([3., 8.])
print(np.column_stack((a, b)))
print("----------------")
print(a[:, newaxis])
print("----------------")
print(b[:, newaxis])
print("----------------")
print(np.column_stack((a[:, newaxis], b[:, newaxis])))
print("----------------")
print(np.hstack((a[:, newaxis], b[:, newaxis])))
print("----------------")

[[2. 4. 2.]
 [3. 3. 4.]
 [4. 2. 6.]]
----------------
[[6. 4. 0.]
 [6. 2. 7.]
 [5. 2. 0.]]
----------------
[[2. 4. 2. 6. 4. 0.]
 [3. 3. 4. 6. 2. 7.]
 [4. 2. 6. 5. 2. 0.]]
----------------
[[4. 3.]
 [2. 8.]]
----------------
[[4.]
 [2.]]
----------------
[[3.]
 [8.]]
----------------
[[4. 3.]
 [2. 8.]]
----------------
[[4. 3.]
 [2. 8.]]
----------------


np.concatenate([arr1,arr2],axis)  

In [132]:
arr1 = np.random.randint(10,50,[3,4])
arr2 = np.random.randint(10,50,[3,4])
arr1
arr2
np.concatenate([arr1,arr2],1)  #1-表示横向操作-拼接列
np.concatenate([arr1,arr2],0)  #0-表示纵向操作-拼接行

array([[28, 27, 46, 41],
       [37, 21, 42, 42],
       [34, 35, 25, 39]])

array([[31, 12, 30, 41],
       [19, 16, 43, 46],
       [49, 36, 15, 37]])

array([[28, 27, 46, 41, 31, 12, 30, 41],
       [37, 21, 42, 42, 19, 16, 43, 46],
       [34, 35, 25, 39, 49, 36, 15, 37]])

array([[28, 27, 46, 41],
       [37, 21, 42, 42],
       [34, 35, 25, 39],
       [31, 12, 30, 41],
       [19, 16, 43, 46],
       [49, 36, 15, 37]])

### 矩阵拆分

numpy.hsplit(ary, indices_or_sections)

In [129]:
import numpy as np

x = np.arange(16.0).reshape(4, 4)
print(x)
print("-------------")
print(np.hsplit(x, 2))
print("-------------")
print(np.hsplit(x, np.array([3, 6])))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
-------------
[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]
-------------
[array([[ 0.,  1.,  2.],
       [ 4.,  5.,  6.],
       [ 8.,  9., 10.],
       [12., 13., 14.]]), array([[ 3.],
       [ 7.],
       [11.],
       [15.]]), array([], shape=(4, 0), dtype=float64)]


numpy.vsplit(ary, indices_or_sections)

In [130]:
import numpy as np

x = np.arange(16.0).reshape(4, 4)
print(x)
print("-------------")
print(np.vsplit(x, 2))
print("-------------")
print(np.vsplit(x, np.array([3, 6])))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
-------------
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
-------------
[array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]]), array([], shape=(0, 4), dtype=float64)]


# Pandas

概览：
1. Series
   - 基本操作
   - 与df的转换
2. Dataframe
   - 基本操作
3. 文件读取
4. Pandas内置绘图模块
5. 数据透视表（pivot_table函数）
6. Examples w/ solutions

## Series

##### 数据结构-series
*******************
- 类似一维数组的对象   
   -构建Series   
   -通过数组/列表
   -通过dict
- 预览数据，ser_obj.head()
- 由数据和索引组成
   -索引在做，数据在右
   -索引自动创建
- 获取数据和索引
   -ser_obj.index, ser_obj.values

### 构造及初始化

In [134]:
import pandas as pd
import numpy as np

In [135]:
pd.Series(range(10,20))  #没有明确指定类型-没有name，index自动生成

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [ ]:
import os

with open('C:/Users/FuYuf/Desktop/data2.csv','r',encoding='utf-8') as f1,open('C:/Users/FuYuf/Desktop/test.txt','w',encoding='utf-8') as f2:
    f2.write('this is a line')
f2.close()

In [136]:
d = {'a':0.,'b':1,'c':2}  #dictionary   - key就是index
pd.Series(d)

a    0.0
b    1.0
c    2.0
dtype: float64

In [137]:
pd.Series(np.random.rand(5))  #ndarray

0    0.815581
1    0.415413
2    0.273306
3    0.310422
4    0.690355
dtype: float64

### 预览

In [138]:
ser_obj =  pd.Series(np.random.rand(100))
ser_obj.head()  #预览前部分

0    0.269540
1    0.192913
2    0.642710
3    0.686771
4    0.317422
dtype: float64

In [139]:
ser_obj.tail()  #预览后部分

95    0.459834
96    0.592796
97    0.258940
98    0.229387
99    0.525127
dtype: float64

In [140]:
ser_obj.index

RangeIndex(start=0, stop=100, step=1)

In [153]:
ser_obj.values   #panda把value用ndarray表示了

array([0.17033991, 0.64173527, 0.30917266, 0.81183878, 0.00475936,
       0.38792893, 0.29598302, 0.64367571, 0.27888243, 0.62598332,
       0.3323882 , 0.79758761, 0.26969967, 0.74934549, 0.85103393,
       0.20670038, 0.28109338, 0.48631273, 0.28132858, 0.52880323,
       0.94237039, 0.20863895, 0.44755197, 0.82771501, 0.8482296 ,
       0.44103156, 0.31078624, 0.86560916, 0.92110432, 0.26130783,
       0.88270971, 0.78820607, 0.95213631, 0.06714488, 0.43485847,
       0.97678253, 0.82009987, 0.86243435, 0.87497778, 0.09284739,
       0.54766865, 0.28442673, 0.45618088, 0.85326855, 0.14651319,
       0.49115972, 0.04730159, 0.68806588, 0.64172867, 0.51532307,
       0.53431381, 0.66589751, 0.25844381, 0.03809185, 0.3328918 ,
       0.01534896, 0.66894517, 0.14431097, 0.34308731, 0.1934026 ,
       0.41193359, 0.33063321, 0.23540064, 0.73286523, 0.51196398,
       0.71191172, 0.26241213, 0.08552119, 0.9837776 , 0.335557  ,
       0.72246819, 0.43619863, 0.90130706, 0.65693157, 0.75623

In [141]:
ser_obj = pd.Series(np.random.rand(100), name='rand_num')   #数据名称起名为rand_num 
ser_obj.head(10)

0    0.170340
1    0.641735
2    0.309173
3    0.811839
4    0.004759
5    0.387929
6    0.295983
7    0.643676
8    0.278882
9    0.625983
Name: rand_num, dtype: float64

### 索引及切片

Series 索引切片
- 行索引：

   - 按索引位置：ser_obj[pos]

   - 按索引名称：ser_obj[‘label’]

- 切片索引：

   - 按索引位置：ser_obj[2:4]

   - 按索引名称：ser_obj[‘label1’: ‘label3’]，注意，按索引名切片操作时，是包含终止

- 不连续索引：

   - ser_obj[ [‘label1’, ‘label2’, ‘label3’] ]

   - ser_obj[ [pos1, pos2, pos3] ]

In [142]:
ser_obj.index.name = 'index1'  #给index起名字index1

In [143]:
ser_obj.head()

index1
0    0.170340
1    0.641735
2    0.309173
3    0.811839
4    0.004759
Name: rand_num, dtype: float64

In [145]:
ser_obj3 = pd.Series(np.random.rand(5),index = ['a','b','c','d','e'])  #指定index名称
ser_obj3

a    0.761298
b    0.691588
c    0.008458
d    0.153350
e    0.458536
dtype: float64

In [146]:
ser_obj3.loc['b']   #location索引位置获取位置 ser_obj3["b"]

0.6915879397443937

In [147]:
'a' in ser_obj3  #判断a是否在Series中

True

In [148]:
ser_obj3[0]

0.7612977615493633

In [149]:
ser_obj3.iloc[0]  #建议用loc,iloc获取数据，iloc是通过索引位置（integer）获取数据

0.7612977615493633

In [150]:
#字符串数据
countries = ['China', 'American', 'Australia',None]
pd.Series(countries)

0        China
1     American
2    Australia
3         None
dtype: object

In [152]:
numbers = [4, 5, 6, None]
pd.Series(numbers)      #Nan = not a number

0    4.0
1    5.0
2    6.0
3    NaN
dtype: float64

In [186]:
ser_obj
ser_obj[1:3]   #跟列表一样，左闭右开

a    0
b    1
c    2
d    3
e    4
dtype: int64

b    1
c    2
dtype: int64

In [187]:
ser_obj['b':'d']  #用索引名称是全闭区间，包含终止索引

b    1
c    2
d    3
dtype: int64

不连续索引，把要的索引用list列出来

In [188]:
ser_obj[ [0,2,4] ]  

a    0
c    2
e    4
dtype: int64

In [189]:
ser_obj[ ['b','c','e']]

b    1
c    2
e    4
dtype: int64

## DataFrame

数据结构--Data Frame
- 类似多为数组/表格数据
- 每列数据类型可以不填
- 索引包括行（index）和列（label/column）

1. 构建DataFrame

   通过ndarray/列表
   通过dict
2. 获取列数据（Series类型 ）

   df_obj[label] 或 df_obj.label

3. 增加列数据

   df_obj[new_label] = data

4. 删除列

   df_obj.drop(columns=[],inplace=False)，当inplace=True时，原数据不会改变，否则不变。
   del df_obj[col_idx]

### 构建

In [155]:
import pandas as pd
import numpy as np

In [156]:
df_obj = pd.DataFrame(np.random.randn(5,4))
df_obj      #行列索引会自动加上的

0         1         2         3
0 -1.205980  1.376513  0.149226  0.636995
1  2.202574  0.033766  1.167885  1.433959
2 -1.335866  0.099710  0.199201 -0.817575
3  1.415094 -1.052258  0.514599 -0.619634
4  0.487596 -0.846936  0.200063  1.408466

In [157]:
print(df_obj)   #print是不带渲染效果的输出，与上面作用等价

          0         1         2         3
0 -1.205980  1.376513  0.149226  0.636995
1  2.202574  0.033766  1.167885  1.433959
2 -1.335866  0.099710  0.199201 -0.817575
3  1.415094 -1.052258  0.514599 -0.619634
4  0.487596 -0.846936  0.200063  1.408466


In [158]:
dict_data = {'A': 1.,
             'B': pd.Timestamp('20190101'),
             'C': pd.Series(1, index = list(range(4)),dtype = 'float32'),
             'D': np.array([3] * 4, dtype = 'int32'),
             'E':['Python','Java','C++','C#'],
             'F': 'Chinahadoop' }
print(dict_data)  #按列创建，也可以按行创建（嵌套列表）

{'A': 1.0, 'B': Timestamp('2019-01-01 00:00:00'), 'C': 0    1.0
1    1.0
2    1.0
3    1.0
dtype: float32, 'D': array([3, 3, 3, 3]), 'E': ['Python', 'Java', 'C++', 'C#'], 'F': 'Chinahadoop'}


In [159]:
df_obj2 = pd.DataFrame(dict_data)
df_obj2

A          B    C  D       E            F
0  1.0 2019-01-01  1.0  3  Python  Chinahadoop
1  1.0 2019-01-01  1.0  3    Java  Chinahadoop
2  1.0 2019-01-01  1.0  3     C++  Chinahadoop
3  1.0 2019-01-01  1.0  3      C#  Chinahadoop

Dataframe偏向于列先操作，取出列以后就是式series操作

--------------------------

### 数据预览

In [160]:
df_obj2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [161]:
df_obj2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [162]:
df_obj2.values

array([[1.0, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'Python',
        'Chinahadoop'],
       [1.0, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'Java',
        'Chinahadoop'],
       [1.0, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'C++',
        'Chinahadoop'],
       [1.0, Timestamp('2019-01-01 00:00:00'), 1.0, 3, 'C#',
        'Chinahadoop']], dtype=object)

In [163]:
df_obj2.head(3)

A          B    C  D       E            F
0  1.0 2019-01-01  1.0  3  Python  Chinahadoop
1  1.0 2019-01-01  1.0  3    Java  Chinahadoop
2  1.0 2019-01-01  1.0  3     C++  Chinahadoop

In [164]:
df_obj2.tail()  

A          B    C  D       E            F
0  1.0 2019-01-01  1.0  3  Python  Chinahadoop
1  1.0 2019-01-01  1.0  3    Java  Chinahadoop
2  1.0 2019-01-01  1.0  3     C++  Chinahadoop
3  1.0 2019-01-01  1.0  3      C#  Chinahadoop

In [165]:
df_obj2['A']

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

增/减列

In [166]:
df_obj2['G'] = range(4)
df_obj2

A          B    C  D       E            F  G
0  1.0 2019-01-01  1.0  3  Python  Chinahadoop  0
1  1.0 2019-01-01  1.0  3    Java  Chinahadoop  1
2  1.0 2019-01-01  1.0  3     C++  Chinahadoop  2
3  1.0 2019-01-01  1.0  3      C#  Chinahadoop  3

In [168]:
df_obj3 = df_obj2.drop(columns = ['B','G'])  #drop-Note：pandas操作完以后要有变量接收它，因为结果操作的返回值，原数据不会改变
df_obj3

A    C  D       E            F
0  1.0  1.0  3  Python  Chinahadoop
1  1.0  1.0  3    Java  Chinahadoop
2  1.0  1.0  3     C++  Chinahadoop
3  1.0  1.0  3      C#  Chinahadoop

In [169]:
del df_obj2['A']
df_obj2          #del是在原始数据上操作，但用的比较少，推荐drop

B    C  D       E            F  G
0 2019-01-01  1.0  3  Python  Chinahadoop  0
1 2019-01-01  1.0  3    Java  Chinahadoop  1
2 2019-01-01  1.0  3     C++  Chinahadoop  2
3 2019-01-01  1.0  3      C#  Chinahadoop  3

### 索引及切片

Dataframe 索引切片

**依据索引获取数据：**
- 列索引：df_obj[‘label’]

- 不连续列索引：df_obj[ [‘label1’, ‘label2’] ]

- 行索引，loc[ ]，iloc[ ]

**Inplace参数：**

- Pandas中的很多操作都有参数inplace，如 drop()，replace() …

- 默认 inplace=False，表示将操作后的结果进行返回，对原始数据不会产生影响

- inplace=True，没有返回值，在原始数据上进行操作，对原始数据会产生影响

In [191]:
#构建dataframe
country1 = pd.Series({'Name':'China',
                     'Language':'Chinese',
                     'Area':'9.597 M km2',
                     'Happiness Rank':79})

country2 = pd.Series({'Name':'American',
                     'Language':'English(US)',
                     'Area':'9.834 M km2',
                     'Happiness Rank':14})
country3 = pd.Series({'Name':'Australia',
                     'Language':'English(AU)',
                     'Area':'7.692M km2',
                     'Happiness Rank':9})

df = pd.DataFrame([country1, country2, country3], index=['CH','US', 'AU'])
df


Name     Language         Area  Happiness Rank
CH      China      Chinese  9.597 M km2              79
US   American  English(US)  9.834 M km2              14
AU  Australia  English(AU)   7.692M km2               9

In [192]:
df['Area']

CH    9.597 M km2
US    9.834 M km2
AU     7.692M km2
Name: Area, dtype: object

In [193]:
df[['Area','Language']]  

Area     Language
CH  9.597 M km2      Chinese
US  9.834 M km2  English(US)
AU   7.692M km2  English(AU)

In [194]:
df.loc['CH']

Name                    China
Language              Chinese
Area              9.597 M km2
Happiness Rank             79
Name: CH, dtype: object

In [195]:
type(df.loc['CH'])

<class 'pandas.core.series.Series'>

In [196]:
#先行后列
print(df.loc['CH']['Area'])
print(df.loc['CH'].loc['Area'])
print(df.iloc[0]['Area'])

9.597 M km2
9.597 M km2
9.597 M km2


In [197]:
#先列后行
print(df['Area']['CH'])
print(df['Area'].loc['CH'])
print(df['Area'].iloc[0])

9.597 M km2
9.597 M km2
9.597 M km2


In [200]:
#删除Area列
df2 = df.drop('Area', axis = 1)   #默认inplace = False
df2

Name     Language  Happiness Rank
CH      China      Chinese              79
US   American  English(US)              14
AU  Australia  English(AU)               9

In [201]:
#删除Area列
df2 = df.drop('Area', axis = 1)   #默认inplace = False
df2

Name     Language  Happiness Rank
CH      China      Chinese              79
US   American  English(US)              14
AU  Australia  English(AU)               9

In [202]:
df3 = df.drop('Language', axis = 1, inplace=True)

Pandas中，使用索引获取数据的方式可归纳为3种：

1. .loc，标签索引   

2. .iloc，位置索引

loc与iloc主要用于行索引，其中，使用名称/标签的切片索引是包含末尾位置的。

3. 布尔值遮罩：

对应位置为True的时候，则取得该数据。

Boolean Mask 向量化的字符串操作

In [204]:
#构建dataframe
country1 = pd.Series({'Name':'China',
                     'Language':'Chinese',
                     'Area':'9.597 M km2',
                     'Happiness Rank':79})

country2 = pd.Series({'Name':'American',
                     'Language':'English(US)',
                     'Area':'9.834 M km2',
                     'Happiness Rank':14})
country3 = pd.Series({'Name':'Australia',
                     'Language':'English(AU)',
                     'Area':'7.692M km2',
                     'Happiness Rank':9})

df = pd.DataFrame([country1, country2, country3], index=['CH','US', 'AU'])

In [205]:
#找到说英语的国家
df['Language'].str.contains('English')   

CH    False
US     True
AU     True
Name: Language, dtype: bool

In [207]:
#生成bool值遮罩,只显示True的行，相当于特殊的索引
filter_condition = df['Language'].str.contains('English')
df[filter_condition]

Name     Language         Area  Happiness Rank
US   American  English(US)  9.834 M km2              14
AU  Australia  English(AU)   7.692M km2               9

In [206]:
#过滤出排名前20名的国家,带条件的遮罩进行特殊索引
df[df['Happiness Rank'] <= 20]  

Name     Language         Area  Happiness Rank
US   American  English(US)  9.834 M km2              14
AU  Australia  English(AU)   7.692M km2               9

### 运算与对齐

运算与对齐
- Series的运算：

   - 对齐操作发生在索引上

- DataFrame的运算：

   - 对齐操作会同时发生在行和列上，注意：Series和DataFrame操作时，Series被看作行数据（index被看作列），和DataFrame中的每行数据进行计算。

- Series和DataFrame的对齐和运算方式：

   1. 索引与数据的对应关系仍保持在数组运算的结果中。

   2. 若是没有对齐的位置，则运算结果位置默认补NaN

In [208]:
ser1 = pd.Series(range(10,20), index=range(10))
ser1

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [209]:
ser2 = pd.Series(range(20,25), index=range(5))
ser2

0    20
1    21
2    22
3    23
4    24
dtype: int64

In [210]:
ser1 +ser2

0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64

In [211]:
df1 = pd.DataFrame(np.ones((2,2)),columns = ['a','b'])  #注意ones有2层括号
df1

a    b
0  1.0  1.0
1  1.0  1.0

In [212]:
df2 = pd.DataFrame(np.ones((3,3)),columns = ['a','b','c'])
df2

a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0

In [213]:
df1+df2

a    b   c
0  2.0  2.0 NaN
1  2.0  2.0 NaN
2  NaN  NaN NaN

In [214]:
ser2
df1
ser2+df1

0    20
1    21
2    22
3    23
4    24
dtype: int64

a    b
0  1.0  1.0
1  1.0  1.0

a   b   0   1   2   3   4
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN

In [215]:
ser3 = pd.Series([1, 2, 3],index=['a','b','c'])
ser3

a    1
b    2
c    3
dtype: int64

In [216]:
ser3 + df1  #series的index和dataframe的column进行计算

a    b   c
0  2.0  3.0 NaN
1  2.0  3.0 NaN

**map(function,series)**

- 作用：将funciton函数作用于一个Series的每一个元素

Series：是待分析的数据

function函数： 1. 可以是NumPy中的通用函数(np.max、np.mean等)

          2. 可以是自定义函数(def function)

   - 优点：不使用循环，代码简洁，效率高

In [219]:
import pandas as pd
import math
import numpy as np

In [220]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


用python自带的map函数，操作返回的是一个object，记录的是操作的过程/步骤——我要将l中的每个元素开根号，但是这个操作没有进行。直到访问数据结果的值的时候才会执行

In [221]:
result = map(math.sqrt, l)
print(result)  #第一个参数是不加括号的函数名，第二个参数是对象（变量名）

In [222]:
print(list(result))

[0.0, 1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 2.8284271247461903, 3.0]


In [223]:
ser = pd.Series(l)
ser

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [224]:
#调用通用函数
ser.map(math.sqrt) 

0    0.000000
1    1.000000
2    1.414214
3    1.732051
4    2.000000
5    2.236068
6    2.449490
7    2.645751
8    2.828427
9    3.000000
dtype: float64

In [225]:
#调用通用函数
ser.map(math.sqrt) 

0    0.000000
1    1.000000
2    1.414214
3    1.732051
4    2.000000
5    2.236068
6    2.449490
7    2.645751
8    2.828427
9    3.000000
dtype: float64

也可以显示的定义一个较复杂的函数

In [226]:
def func(x):
    x1 = x**3
    x2 =x1*2 + 1
    return x2

In [227]:
ser.map(func)

0       1
1       3
2      17
3      55
4     129
5     251
6     433
7     687
8    1025
9    1459
dtype: int64

**apply()函数**

- 通过apply()将函数应用到行或列上

- 在DataFrame上操作时注意指定轴的方向，默认axis=0

**applymap()函数**

- 通过applymap()将函数应用到对象的元素上，df的维度不变

In [229]:
df = pd.DataFrame(np.arange(10).reshape(5,2), columns=['col_1','col_2'])
df

col_1  col_2
0      0      1
1      2      3
2      4      5
3      6      7
4      8      9

In [230]:
df.apply(np.sum)

col_1    20
col_2    25
dtype: int64

In [231]:
df.apply(np.sum, axis =1)

0     1
1     5
2     9
3    13
4    17
dtype: int64

In [232]:
df.apply(np.sum)

col_1    20
col_2    25
dtype: int64

In [233]:
df.apply(np.sum, axis =1)

0     1
1     5
2     9
3    13
4    17
dtype: int64

In [234]:
df.applymap(np.sqrt)

col_1     col_2
0  0.000000  1.000000
1  1.414214  1.732051
2  2.000000  2.236068
3  2.449490  2.645751
4  2.828427  3.000000

In [235]:
staff_df = pd.DataFrame([{'name':'zhangsan','department':'development'},
                        {'name':'lisi','department':'finance'},
                        {'name':'zhaoliu','department':'marketing'}])
staff_df

name   department
0  zhangsan  development
1      lisi      finance
2   zhaoliu    marketing

In [236]:
#get Last name
staff_df['lastName'] = staff_df['name'].apply(lambda x: x[0])
staff_df

name   department lastName
0  zhangsan  development        z
1      lisi      finance        l
2   zhaoliu    marketing        z

In [238]:
staff_df['LastName'] = staff_df['name'].map(lambda x: x[0])
staff_df

name   department lastName LastName
0  zhangsan  development        z        z
1      lisi      finance        l        l
2   zhaoliu    marketing        z        z

## Index对象

数据结构--Index

Series和DataFrame中的索引都是Index对象

Index对象的特征：

- 不可变(immutable) ，保证了数据的安全

- 常见的Index种类：

   - Index

   - Int64Index

   - MultiIndex，“层级”索引

   - DatetimeIndex，时间戳类型   用于时间序列的处理-股票

- Index对象重置索引：

   - reset_index(drop)，将索引重新赋值为0-1

In [173]:
ser_obj = pd.Series(range(10,20,2))
ser_obj

0    10
1    12
2    14
3    16
4    18
dtype: int64

In [174]:
ser_obj.index

RangeIndex(start=0, stop=5, step=1)

In [175]:
ser_obj.index[2]  # index[2]元素不可以赋值

2

In [176]:
ser_obj = pd.Series(range(10,20,2),index = ['a','b','c','d','e'] )
ser_obj

a    10
b    12
c    14
d    16
e    18
dtype: int64

In [177]:
ser_obj.reset_index()   

index   0
0     a  10
1     b  12
2     c  14
3     d  16
4     e  18

In [178]:
type(ser_obj.reset_index())   

<class 'pandas.core.frame.DataFrame'>

In [179]:
ser_obj.reset_index(drop=True)

0    10
1    12
2    14
3    16
4    18
dtype: int64

In [180]:
type(ser_obj.reset_index(drop=True))

<class 'pandas.core.series.Series'>

In [181]:
ser_obj = pd.Series(range(5), index = ['a','b','c','d','e'])
ser_obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [182]:
#ser_obj['b']
ser_obj.loc['b']

1

In [183]:
ser_obj.iloc[2]

2

**按索引排序：sort_index()**

- ascending：默认为True，True 升序，False 降序

- axis：默认为0，0表示按列索引，1表示按行索引

**对DataFrame操作时注意轴方向**

**按值排序：sort_values(by, ascending)**

1. 按单列的值排序

   - axis：默认为0，0表示按列索引，1表示按行索引

   - by=‘label’，by的值选取，与axis的轴方向有关系，当axis=0，表示从列索引的标签中选取标签，axis=1时，表示从行索引的标签中选取标签。

   - ascending：默认为True，True 升序，False 降序

2. 按多列的值排序，by=[  ]，ascending = [ ]，by的长度必须和ascending的长度必须一致，且是一一对应的关系。

In [ ]:
#默认axis=0,表示按行排序   默认ascending=True升序
data.sort_index(ascending=False).head(10)

In [ ]:
data.sort_index(axis=1).head()

In [ ]:
#单列排序
data.sort_values(by='Country').head(10)

In [ ]:
#按多列排序
data.sort_values(by=['Region','Country'],ascending =[True,False]).head(10)

## 文件读取

**读取数据**：
- pd.read_csv(filepath, usecols, index_col) 

- filepath: 文件路径

- usecols: 指定需要读取的列（默认全部读取）

- index_col: 指定某列为索引列，默认会生成一列索引 0, 1, …

- df.info()：

快速查看数据基本信息

**保存数据**：
- df.to_csv(filepath, index) 

- filepath: 保存的路径

- index: 是否将索引列保存，默认为True

In [ ]:
filepath = ''

In [ ]:
data = pd.read_csv(filepath, usecols=['Country', 'Region','Happiness Rank', 'Happiness Score'], index_col = 'Country')#usecols 指定内容

In [ ]:
data.to_csv('./data_with_index.csv')
data.to_csv('./data_no_index.csv',index = False)

# Matplotlib

- 画图步骤
- 自定义绘图函数
- 引申html绘图—Boken


# Seaborn

- 不同类型的图的写法

# Cases Analysis Steps

## Overview
1. 读取数据
2. 查看数据统计信息(.head()/.info()/.columns/.describe())
3. 数据清洗
   - 查看缺失值(.isnull())
   - 删除缺失值（.drop(columns=[])）
   - 填充缺失值（.fillna()）
4. 统计分析（分组、聚合、np统计计算）
5. 数据的预处理(清洗、填充、校正)
6. 有效特征的构建
7. 数据可视化
8. 初步选择模型

## Start Analysis
导入需要的包

In [1]:
# 导入数据分析包
import numpy as np
import pandas as pd

# 导入绘图工具包
import matplotlib.pyplot as plt
import seaborn as sns

# 导入日期时间变量处理相关的工具包
import calendar
from datetime import datetime

# 绘图设置
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

数据上手三部曲:
- 了解数据大小
- 查看前几行/最后几行数
- 查看数据类型与缺失值

读取数据

In [ ]:
# 读取数据
titanic_df = pd.read_csv('../data/titanic.csv')

统计信息

1. 数值变量

In [ ]:
titanic_df[["Survived","Age", "SibSp", "Parch"]].describe()

2. 分类变量

**使用include=[np.object]来查看分类变量**
- count: 非缺失值的个数
- unique: 非重复值得个数
- top: 最高频值
- freq: 最高频值出现次数

In [ ]:
titanic_df.describe(include=[np.object])